
music = {
        "iraaday": "https://www.youtube.com/watch?v=Qwm6BSGrOq0",
        "apa": "https://www.youtube.com/watch?v=l7q_WH2cbS0&pp=ygUSYXBhIG1pbGFuZ2UgamFyb29y",
        "kaise": "https://www.youtube.com/watch?v=uC1iJcYOyeY&pp=ygUda2Fpc2UgbXVqaGUgdHVtIG1pbCBnYXllIHNvbmc%3D",
        "hosanna": r"C:\Users\Welcome 421\Music\Hosanna_Best_Video___Ekk_Deewana_Tha___Amy_Jackson___Prateik_Babbar___Leon___Suzanne(256k).mp3",
        "mere" : r"C:\Users\Welcome 421\Music\Mere_Bina_Full_Video_-_Crook_Emraan_Hashmi%2CNeha_Sharma_Nikhil_D_Souza_Pritam_Mukesh_Bhatt(256k).mp3",
        "saibo": r"C:\Users\Welcome 421\Music\Saibo_Full_Video_-_Shor_In_The_City_Radhika_Apte%2CTusshar_Shreya_Ghoshal%2CTochi_Raina(256k).mp3",
        "dildara": r"C:\Users\Welcome 421\Music\Dildara_Song___Ra.One___ShahRukh_Khan%2C_Kareena_Kapoor(256k).mp3",
        "afeemi": r"C:\Users\Welcome 421\Music\Afeemi___Full_Song___Meri_Pyaari_Bindu___Ayushmann%2C_Parineeti___Sanah___Sachin-Jigar___Kausar_Munir(128k).m4a",
        "raanjhanaa": r"C:\Users\Welcome 421\Music\Raanjhanaa_Hua_Mai_Tera__Video_Song____Raanjhanaa___Dhanush___Sonam_Kapoor(256k).mp3",
        "aaj" : r"C:\Users\Welcome 421\Music\AAJ_DIN_CHADHEYA_-_Full_Audio_Song____Love_Aaj_Kal___Saif_Ali_Khan___Giselli_Monteiro(256k).mp3",
        "chaudhari": r"C:\Users\Welcome 421\Music\Chaudhary_-_Amit_Trivedi_feat_Mame_Khan,_Coke_Studio_@_MTV_Season_2(256k).mp3",
        "shaayeraana": r"C:\Users\Welcome 421\Music\Aaj_dil_Shaayraana_-_Arijit_Singh___Holiday___Akshay_Kumar___Sonakshi_Sinha___Pritam___Irshad_K(256k).mp3",
        "be": r"C:\Users\Welcome 421\Music\Be_Intehaan___Atif___Sunidhi___Saif_Ali_Khan___Deepika_Padukone___Race_2(256k).mp3",
        "pal": r"C:\Users\Welcome 421\Music\Blackmail_-_Pal_Pal_Dil_Ke_Paas_Tum_Rehti_Ho_-_Kishore_Kumar(128k).mp3",
        "bolna": r"C:\Users\Welcome 421\Music\Blackmail_-_Pal_Pal_Dil_Ke_Paas_Tum_Rehti_Ho_-_Kishore_Kumar(128k).mp3",
        "chain": r"C:\Users\Welcome 421\Music\Chain__Sanu_Ik_Pal_Chain__Full_Lyrical_Video_Song___Shivai_Vyas___Bawa_Gulzar___T-Series(256k).mp3",
        "darmiyaa": r"C:\Users\Welcome 421\Music\Darmiyaan_Hindi_Song_from_Jodi_Breakers_movie(256k).mp3",
        "dekh": r"C:\Users\Welcome 421\Music\DEKH_LENA_Full_Song__Audio____Arijit_Singh%2C_Tulsi_Kumar___Tum_Bin_2(256k).mp3",
        "dekha": r"C:\Users\Welcome 421\Music\Dekha_Hazaro_Dafaa___Rustom___Akshay_Kumar___Ileana_D_cruz___Arijit_Singh_%2C_Palak_M__Jeet_Gannguli(256k).mp3",
        "dhoonde": r"C:\Users\Welcome 421\Music\Dhoonde_Akhiyaan_-_Full_Video___Jabariya_Jodi___Sidharth_Malhotra%2C_Parineeti_C___Yasser___Altamash(128k).mp3",
        "dil": r"C:\Users\Welcome 421\Music\Dil_Chahte_Ho___Jubin_Nautiyal%2C_Mandy_Takhar___Payal_Dev%2C_A.M.Turaz___Navjit_Buttar___Bhushan_Kumar(256k).mp3",
        "excuses": r"C:\Users\Welcome 421\Music\Excuses__Official_Video____AP_Dhillon___Gurinder_Gill___Intense(256k).mp3",
        "ghar": r"C:\Users\Welcome 421\Music\Ghar_Se_Nikalte_Hi_%5BFull_Song%5D_Papa_Kehte_Hain___Jugal_Hansraj%2C_Mayuri_Kango(128k).m4a",
        "girl": r"C:\Users\Welcome 421\Music\Girl_I_Need_You_Lyrical___BAAGHI___Tiger%2C_Shraddha___Arijit_Singh%2C_Meet_Bros%2C_Roach_Killa%2C_Khushboo(256k).mp3",
        "halka": r"C:\Users\Welcome 421\Music\Halka_Halka_Full_Video___FANNEY_KHAN___Aishwarya_Rai_Bachchan___Rajkummar_Rao___Amit_Trivedi(256k).mp3",
        "hamdard": r"C:\Users\Welcome 421\Music\Hamdard_Full_Video_Song___Ek_Villain___Arijit_Singh___Mithoon(128k).mp3",
        "hans": r"C:\Users\Welcome 421\Music\Hans_Mat_Pagli_Video_Song_With_Lyrics___Toilet-_Ek_Prem_Katha___Akshay_Kumar%2C_Bhumi___Sonu_%2C_Shreya(256k).mp3",
        "ho": r"C:\Users\Welcome 421\Music\Ho_gayi_galti_mujhse_Lyrics(48k).mp3",
        "hoshwalon": r"C:\Users\Welcome 421\Music\Hoshwalon_Ko_Khabar_Kya___Aamir_Khan___Sonali_Bendre___Sarfarosh_Movie___Jagjit_Singh___90_s_Hits(256k).mp3",
        "hua": r"C:\Users\Welcome 421\Music\HUA_HAIN_AAJ_PEHLI_BAAR__Lyrical___SANAM_RE___Pulkit_Samrat%2C_Urvashi_Rautela___Divya_Khosla_Kumar(256k).mp3",
        "hum": r"C:\Users\Welcome 421\Music\Hum_Mar_Jayenge_Full_Video_Song___Aditya_Roy_Kapur%2C_Shraddha_Kapoor(256k).mp3",
        "humko": r"C:\Users\Welcome 421\Music\Humko_Pyaar_Hua_Lyrical_Video___Ready_Ft._Salman%2C_Asin___Tulsi_Kumar%2C_KK___Pritam(256k).mp3",
        "humnava": r"C:\Users\Welcome 421\Music\Humnava_Mere_Full_HD__Video_Song____Sad_Love_Story___Jubin_Nautiyal___Manoj_Muntashir___Bhushan(256k).mp3",
        "i": r"C:\Users\Welcome 421\Music\I_love_you_(Full_song)_Bodyguard_feat._Salman_khan,_Kareena_Kapoor(256k).mp3",
        "iktara": r"C:\Users\Welcome 421\Music\Iktara_Full_Video_-_Wake_Up_Sid_Ranbir_Kapoor%2CKonkona_Sen_Sharma_Kavita_Seth_Amit_Trivedi(128k).mp3",
        "illahi": r"C:\Users\Welcome 421\Music\Illahi_-_Yeh_Jawaani_Hai_Deewani___Ranbir_Kapoor%2C_Deepika_Padukone(128k).mp3",
        "issaq": r"C:\Users\Welcome 421\Music\ISSAQ_TERA(256k).mp3",
        "itni": r"C:\Users\Welcome 421\Music\Itni_Si_Baat_Hain_Full_Song___AZHAR___Emraan_Hashmi%2C_Prachi_Desai___Arijit_Singh%2C_Pritam___T-Series(256k).mp3",
        "jaan": r"C:\Users\Welcome 421\Music\Jaan_Nisaar_-_Lyrical___Kedarnath__Arijit_Singh___Sushant_Singh_Rajput___Sara_Ali_Khan__Amit_Trivedi(256k).mp3",
        "jab": r"C:\Users\Welcome 421\Music\JAB_TAK_Full_Video___M.S._DHONI_-THE_UNTOLD_STORY___Armaan_Malik%2C_Amaal_Mallik__Sushant_Singh_Rajput(256k).mp3",
        "jag": r"C:\Users\Welcome 421\Music\Jag_Ghoomeya_Full_Song___SULTAN___Salman_Khan%2C_Anushka_Sharma___Rahat_Fateh_Ali_Khan%2C_Vishal-Shekhar(256k).mp3",
        "jalte": r"C:\Users\Welcome 421\Music\JALTE_DIYE__Full_VIDEO_song___PREM_RATAN_DHAN_PAYO___Salman_Khan%2C_Sonam_Kapoor___T-Series(256k).mp3",
        "jaanib": r"C:\Users\Welcome 421\Music\Janib__Duet___FULL_AUDIO_Song___Arijit_Singh___Divyendu_Sharma___Dilliwaali_Zaalim_Girlfriend(256k).mp3",
        "jashn": r"C:\Users\Welcome 421\Music\Jashn-E-Bahaaraa(256k).mp3",
        "jogi": r"C:\Users\Welcome 421\Music\Jogi_-_Lyrical__Shaadi_Mein_Zaroor_Aana__Rajkummar_Rao%2CKriti_K_Arko_ft_Aakanksha_Sharma(256k).mp3",
        "jugnu": r"C:\Users\Welcome 421\Music\Jugnu__Official_Video____Nikhita_Gandhi___Akanksha_Sharma(256k).mp3",
        "kabhi": r"C:\Users\Welcome 421\Music\Kabhi_Kabhi_Aditi_Zindagi___Jaane_Tu_Ya_Jaane_Na___A.R._Rahman___Rashid_Ali(128k).mp3",
        "khayaal": r"C:\Users\Welcome 421\Music\Kabhi_Kabhie_Mere_Dil_Mein_-_Amitabh_Bachchan_-_Mukesh_-_Kabhi_Kabhie_[1976](256k).mp3",
        "kaun": r"C:\Users\Welcome 421\Music\Kaun_Disa_Mein_Leke_Chala_Re_Batohiya_-_Nadiya_Ke_Paar_-_Hemlata,_Jaspal_Singh_-_Ravindra_Jain_Songs(128k).mp3",
        "khamoshiya": r"C:\Users\Welcome 421\Music\Khamoshiya__Title_track_Arijit_Singh_khamoshiya__movie_song_%23trending_%23arijitsingh(256k).mp3",
        "khoyaa": r"C:\Users\Welcome 421\Music\Khoya_Khoya__Full_AUDIO_Song___Sooraj_Pancholi%2C_Athiya_Shetty___Hero___T-Series(256k).mp3",
        "kinnaa": r"C:\Users\Welcome 421\Music\Kinna_Sona_Full_AUDIO_Song_-_Sunil_Kamath___Bhaag_Johnny___Kunal_Khemu___T-Series(256k).mp3",
        "kora": r"C:\Users\Welcome 421\Music\Kora_Kagaz_Tha_Yeh_Man_Mera_4K_Video_Song___Lata_Mangeshkar__Kishore_Kumar___Aradhana__Rajesh_Khanna(256k).mp3",
        "laal": r"C:\Users\Welcome 421\Music\Lal_Chunariya_(Full_Song)_Film_-_God_Tussi_Great_Ho(256k).mp3",
        "leja": r"C:\Users\Welcome 421\Music\Leja_Leja_Re__Full_Video_Song__Ustad_Sultan_Khan___Shreya_Ghoshal___Ustad___The_Divas_(256k).mp3",
        "little": r"C:\Users\Welcome 421\Music\Little_Little_Full_Video__Atrangi_Re_%40A._R._Rahman_Akshay_K%2C_Dhanush%2C_Sara_A_K___Hiral_V%2C_Irshad_K(128k).m4a",
        "luka": r"C:\Users\Welcome 421\Music\Luka_Chuppi_Best_Audio_Song_Rang_De_Basanti_Aamir_Khan_Lata_Mangeshkar_Soha(256k).mp3",
        "maan": r"C:\Users\Welcome 421\Music\Maan_Meri_Jaan___Official_Music_Video___Champagne_Talk___King(256k).mp3",
        "main": r"C:\Users\Welcome 421\Music\Main_Hoon_Saath_Tere_-_Arijit_Singh__Shaadi_Mein_Zaroor_Aana_Rajkummar_Rao%2CKriti_Kharbanda_KAG-Jam8(256k).mp3",
        "maiyya": r"C:\Users\Welcome 421\Music\Maiyya_Mainu__From__Jersey__(256k).mp3",
        "manchala": r"C:\Users\Welcome 421\Music\Manchala_Full_Video_-_Hasee_Toh_Phasee_Parineeti%2C_Sidharth_Shafqat_Amanat_Ali%2C_Nupur_Pant(256k).mp3",
        "mast": r"C:\Users\Welcome 421\Music\Mast_Magan_FULL_Video_Song___2_States___Arijit_Singh___Arjun_Kapoor%2C_Alia_Bhatt(256k).mp3",
        "meet": r"C:\Users\Welcome 421\Music\Meet_Na_Mila_Re_Mann_Ka_-_Abhimaan_Song_-_Amitabh_Bachchan_-_Filmigaane(128k).mp3",
        "mera": r"C:\Users\Welcome 421\Music\Mera_Mann_Kehne_Laga_Full_Song_with_Lyrics___Nautanki_Saala___Ayushmann_Khurrana%2CKunaal_Roy_Kapur(256k).mp3",
        "kaafi": r"C:\Users\Welcome 421\Music\Mere_Liye_Tum_Kaafi_Ho___Shubh_Mangal_Zyada_Saavdhan__Ayushman_Khurana%2CJeetu___Tanishk-Vayu(128k).m4a",
        "samne": r"C:\Users\Welcome 421\Music\Mere_Samne_Wali_Khidki_Mein_-_Padosan_-_Saira_Banu,_Sunil_Dutt_&_Kishore_Kumar_-_Old_Hindi_Songs(256k).mp3",
        "muskurane": r"C:\Users\Welcome 421\Music\Muskurane_Video_-_Citylights___Arijit_Singh___Rajkummar_Rao%2C_Patralekha___Jeet_Gannguli(256k).mp3",
        "nainaa": r"C:\Users\Welcome 421\Music\Naina_Da_Kya_Kasoor_-_Full_Video___AndhaDhun___Ayushmann_Khurrana___Radhika_Apte___Amit_Trivedi(128k).mp3",
        "naino": r"C:\Users\Welcome 421\Music\Naino_Ne_Baandhi_-_Full_Video___Gold___Akshay_Kumar___Mouni_Roy___Arko(256k).mp3",
        "namo": r"C:\Users\Welcome 421\Music\Namo_Namo_-_Lyrical___Kedarnath___Sushant_Rajput___Sara_Ali_Khan___Amit_Trivedi___Amitabh_B(256k).mp3",
        "nayan": r"C:\Users\Welcome 421\Music\Nayan_Video_Song___Dhvani_B_Jubin_N___Lijo_G_Dj_Chetas_Manoj_M_Manhar_U___Radhika_Vinay____Bhushan_K(256k).mp3",
        "nazm": r"C:\Users\Welcome 421\Music\Nazm_Nazm_-_Lyrical___Bareilly_Ki_Barfi___Kriti_Sanon%2C_Ayushmann_Khurrana___Rajkummar_Rao___Arko(128k).m4a",
        "neela": r"C:\Users\Welcome 421\Music\Neela_Aasman_So_Gaya__Male____Full_Song___Silsila___Amitabh_Bachchan___Rekha___Shiv-Hari(256k).mp3"
        
    }

